Allow larger common test resources (#355)
Part of https://github.com/krzema12/snakeyaml-engine-kmp/issues/354

Before this change, the build logic took all test resources, and
converted them into Kotlin code that was building a map using a single
expression with using nested `mapOf` function to represent the directory
structure. However, when trying to move existing JVM-specific resources
(there's a lot of them), one could see a failing build with:

```
exception: java.lang.RuntimeException: Error generating class file CommonTestResources.class (compiled from [/Users/piotr/repos/snakeyaml-engine-kmp/build/generated-code-for-resources/src/commonTest/kotlin/CommonTestResources.kt]): Method too large: CommonTestResources.<clinit> ()V
e
```

This change puts every call to `mapOf(...)` or `ByteString.of(...)` into
a separate method, so that now the limitation is either the maximum
number of files/directories in a given directory, or size of a single
file. It should unblock migrating tests to the common source set that
rely on the large number of files (see a work-in-progress PR:
https://github.com/krzema12/snakeyaml-engine-kmp/pull/356).

It was still faster to not use KotlinPoet, but the generated code became
even more ugly. It's likely that I'm going to use KotlinPoet, especially
that I'm planning to extract this functionality into a library.